services:
  streamlit:
    container_name: "streamlit_app"
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - 8501:8501
  
  db:
    image: postgres:latest
    container_name: dtt-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: dtt_data
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  
    ports:
      - "54320:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  